### ISSUE TITLE
Possible Meeting Times

### ISSUE THREAD

**Issue by BMT45** [BMT45/Ferdinand-Magellan-Project#1]
For a meeting,  I can meet right after class on Monday, Wednesday, and Friday an hour before and after class for an hour.   Tuesday and Thursday I can meet anytime before 2:30 and after 5:15.   Weekends I can meet anytime before 3:30.  Let me know as soon as possible what times are good for you so we can meet up to plan out the direction we are going to take on the project.

**Comment by JustinCampbell9** [comment]
My possible meeting times: 
MWF: 10:00 A.M. - 11:00 A.M. , 12:00 P.M. - 3:00 P.M. 
Tu/Th: 10:00 A.M. - 1:00 P.M.

**Comment by RLG95** [comment]
I can meet anytime Tuesday / Thursday, and typically after 3 on Wednesdays.

**Comment by ghbondar** [comment]
Great! It looks like you have overlap at a few different times. Plan on meeting once per week, and writing-up a brief Github Issue about what was discussed and decided. Stay tuned while we determine which student instructor will be working with you.

**Comment by ghbondar** [comment]
@BMT45 @JustinCampbell9 @RLG95 What day and time each week is your group meeting?

**Comment by JustinCampbell9** [comment]
@ghbondar  We will most likely be meeting in the morning on Tuesday and Thursdays.

**Comment by ghbondar** [comment]
@BMT45  @JustinCampbell9  @RLG95 Great! The next Proj. Checkpoint will soon be here! The next step is to find some documents to mark-up, that will be the basis of this project. Push them to this repo and do your project development here.

**Comment by BMT45** [comment]
Would you be able to meet up on Thursday at 11 A.M.?

**Comment by JustinCampbell9** [comment]
Yes

**Comment by RLG95** [comment]
Where are we meeting?

**Comment by JustinCampbell9** [comment]
We can meet in the library and just get one of the rooms upstairs, unless it's not going to take that long.

**Comment by BMT45** [comment]
Sounds good to me

**Comment by BMT45** [comment]
It’s probably gonna be short.  Like half an hour.

**Comment by JustinCampbell9** [comment]
We'll just go to a normal table like we did last time.

**Comment by ghbondar** [comment]
@BMT45 @RLG95 @JustinCampbell9 You might consider meeting at the Center for Digital Text in FOB 131, since it is during Jon's Office Hours, and he can be your project's Project Mentor and offer some guidance.

@jonhoranic

**Comment by ghbondar** [comment]
@BMT45 @RLG95 @JustinCampbell9 ...and of course your meeting is probably over, so please post an issue in your project repo summarizing your meeting and the decisions you've made, and what you want to accomplish before next-week's meeting.
